baseURL: http://example.org/
languageCode: en-us
title: The Heirs of Britain


markup: ## needed for html in your markdown
  goldmark:
    renderer:
      unsafe: true

menus:
  main:
    - name: Home
      url: "/"


build:
  writeStats: true

permalinks:
  sessions: "/:year/:month/:day/:slug"
