baseURL: http://example.org/
languageCode: en-us
title: The Heirs of Britain

markup: ## needed for html in your markdown
  goldmark:
    renderer:
      unsafe: true

params:
  description: "Lorem ipsum dolor sit amet."
  socials:
    - icon: "fas fa-rss"
      url: "#"

menus:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: Sessions
      url: "/sessions"
      weight: 2
build:
  writeStats: true

permalinks:
  sessions: "/:year/:month/:day/:slug"

outputs:
  home:
    - html
    - rss
    - json
  page:
    - html
